import theme from "../../config/color";
const styles = {
  mainContainer: {
    // flex: 1,
    padding: 5,
    height: "100%",
    paddingX: 10,
    paddingLeft: 40,
    paddingBottom: 10,
    widht:'100%',
  },
  secondFlex: {
    flex: 2,
    paddingX: 5,
    borderLeftWidth: 1,
    background: "#fff",
    borderColor: "lightgray",
  },
  formFlex: {
    width: "70%",
    paddingX: 20,
    paddingLeft: 10,
    background: "#fff",
    flexDirection: "column",
  },
  txtRegistered: {
    color: "black",
    marginLeft: 4,
    fontSize: "xl",
    paddingY: 5,
    fontWeight: "bold",
  },
  mainFormFlex: {
    // flex: 2,
    height: "100%",
    width: "100%",
    paddingX: 5,
    paddingTop: 5,
    paddingBottom: 5,
    marginRight: "20",
    flexDirection: "column",
  },
  txtName: {
    color: "black",
    marginTop: "2",
    fontWeight: "normal",
  },
  simpleGridFlex: {
    columns: 2,
    spacing: 3,
    color: "black",
  },
  firstGrid: {
    height: "80px",
    fontSize: "12px",
    fontWeight: "normal",
  },
  firstGrid1: {
    height: "80px",
    fontSize: "12px",
    fontWeight: "normal",
    flex: 1,
    flexDirection: "column",
  },
  userNamePasswordContainer: {
    flex: 1,
    // paddingX: "5",
    color: "black",
    flexDirection: "column",
  },
  uploadCompany: {
    paddingBottom: 5,
    // flexDirection: "column",
  },
  textIE: {
    paddingY: 5,
    fontSize: "10px",
  },
  uploadAttachments: {
    padding: 1,
    marginX: 10,
    borderWidth: 2,
    width: "100%",
    maxWidth: "300px",
    borderRadius: "5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    borderColor: "gray",
    borderStyle: "dashed",
  },
  iconStyle: {
    size: "40px",
    color: "gray",
    fontSize: "14px",
  },
  btnContinue: {
    // size: "sm",
    width: "300" / 2.2,
    height: "7",
    marginTop: "10",
    alignSelf: "end",
    backgroundColor: theme.customColors.masterpanelColors[100],
  },
  btnPreview: {
    // size: "sm",
    height: "7",
    marginRight: 2,
    alignSelf: "end",
    marginTop: "10",
    width: "300" / 2.2,
    backgroundColor: "#f6f5fa",
  },
  btnBack: {
    // size: "sm",
    marginLeft: 4,
    width: "300" / 3,
    marginY: "4",
    height: "7",
    alignSelf: "left",
    backgroundColor: theme.customColors.masterpanelColors[100],
  },
  flexTextBold: {
    fontSize: "12px",
    fontWeight: "normal",
  },
  hideShowBtn: {
    size: "sm",
    h: "1.5rem",
    colorScheme: "black",
    borderColor: "white",
    justifyContent: "center",
  },
  errorMsg: {
    color: "red",
    marginTop:5,
    fontSize: "14px",
    boxShadow: "sm",
    fontWeight:"bold",
    textAlign: "center",
  },
  mandatoryStar: {
    color: "red",
    paddingRight: 1,
    fontWeight: "700",
    fontSize: "large",
  },
  radioBtn: {
    size: "sm",
    // value: "1",
    bgPos: "right",
    spacing: "20%",
    marginRight: "5",
    colorScheme: "gray",
    color: "#03eded",
    // backgroundColor: "#03eded",
  },
  iconAdd: {
    w: 6,
    h: 3,
    marginY: 5,
    fontSize: "sm",
    color: "#da1c18",
    cursor: "pointer",
    boxShadow: "lg",
  },
  iconClose: {
    w: 4,
    h: 4,
    color: "#da1c18",
    cursor: "not-allowed",
  },
  phaseQuestion: {
    spacing: 8,
    columns: 2,
    paddingY: 2,
    paddingX: 4,
    width: "100%",
  },
  mandatoryStar: {
    color: "red",
    paddingRight: 1,
    fontWeight: "700",
    fontSize: "large",
  },
  centerdFields: {
    alignItems: "center",
    justifyContent: "center",
  },
  stackRadioBtn: {
    spacing: 2,
    marginTop: "2",
    paddingLeft: 2,
    // color: "#C0C0C0",
    direction: "column",
    fontSize: "15px",
  },
  inputFieldsOfMany: {
    width: "100%",
    fontSize: "sm",
    color: "black",
  },
  dropZoneRender: {
    padding: 5,
    alignItems: "center",
    flexDirection: "column",
  },
  phaseInputs: {
    size: "sm",
    color: "black",
    variant: "filled",
    borderWidth: 0,
    backgroundColor: "white",
  },
  backTxt: {
    color: "white",
    fontSize: "12px",
    fontWeight: "bold",
  },
  txtIndustry: {
    marginBottom: 4,
  },
  industrySelect: {
    d: "flex",
    size: "xs",
    height: 10,
    marginRight: 1,
    variant: "filled",
    borderRadius: "5",
  },
  pdfBtn: {
    height: "7",
    marginY: "4",
    color: "white",
    fontSize: "14px",
    width: "300" / 2,
    backgroundColor: theme.customColors.masterpanelColors[100],
  },
  dropzone: {
    scrollBehavior: "auto",
    // padding: "10px",
    minWidth: "60px",
    maxWidth: "150px",
    minHeight: "120px",
    maxHeight: "150px",
    borderRadius: "20px",
    overflow: "auto",
    // overflowY: "auto",
    borderColor: "transparent",
    scrollbarColor: "gray",
  },
};
export default styles;
